dist: trusty

language: java

jdk:
  - oraclejdk8
  - openjdk11

cache:
  directories:
    - .autoconf
    - $HOME/.m2

install: true

script:
  - cd api
  - mvn -U -C -Pstaging,oss-release -Dnon.final=true -Dgpg.skip=true clean verify
  - cd ..
  - mvn -U -C -Pstaging,oss-release -Dnon.final=true -Dgpg.skip=true clean verify

