dist: bionic

language: java

jdk:
  - openjdk11
  - openjdk15

cache:
  directories:
    - .autoconf
    - $HOME/.m2

install: true

script:
  - cd api
  - mvn -U -C -Pstaging,oss-release -Dnon.final=true -Dgpg.skip=true clean install
  - cd ..
  - mvn -U -C -Pstaging,oss-release,all -Dnon.final=true -Dgpg.skip=true clean install
  - cd tck
  - mvn -U clean install
  - cd ../impl-tck
  - mvn -U clean test

