remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta JSON Processing (JSON-P)]
description: [Jakarta JSON Processing API and Compatible Implementation]

links:
  source: https://github.com/eclipse-ee4j/jsonp
  #docs: documentation
  javadocs: docs/api/?overview-summary.html
  download: https://github.com/eclipse-ee4j/jsonp/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/jsonp-dev
  #faq: FAQ
